spring:
  main:
    banner-mode: console

jwt:
  secret: aebong-store-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256
  access-token-validity-seconds: 1800
  refresh-token-validity-seconds: 604800

---

spring.config.activate.on-profile: test
server.port: 8880

---

spring.config.activate.on-profile: local
server.port: 8081

---

spring.config.activate.on-profile: dev
server.port: 8080

---

spring.config.activate.on-profile: prod
server.port: 8080